# Generated by Django 4.2.25 on 2025-11-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_meta_description_blogpost_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
