# Generated by Django 4.2.28 on 2026-02-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_delete_blospost'),
        ('blog', '0009_blogpost_author'),
    ]

    operations = [
    ]
